# Generated by Django 6.0.2 on 2026-02-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('embedding_vector', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField(unique=True)),
                ('topic', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=50)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('embedding_vector', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
