# Generated by Django 6.0.2 on 2026-03-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = []
