# Generated by Django 5.2.8 on 2026-03-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20260312_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonchunk',
            name='embedding_vector',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='lessonprofile',
            name='embedding_vector',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
