# Generated by Django 5.2.8 on 2026-03-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lessonchunk_embedding_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonchunk',
            name='lesson_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lessonprofile',
            name='lesson_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
