# Generated by Django 6.0.2 on 2026-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticquizattempt",
            name="difficulty_tier",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
