# Generated by Django 5.2.8 on 2026-03-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_diagnostic_attempt_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticquestion',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagnosticquizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticquizattempt',
            name='duration_seconds',
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name='diagnosticquizattempt',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosticquizattempt',
            name='raw_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='diagnosticquizattempt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticquizattempt',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosticquizattempt',
            name='violation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagnosticquizattempt',
            name='weighted_score',
            field=models.FloatField(default=0),
        ),
    ]
