# Generated by Django 5.2.8 on 2026-03-01 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_diagnosticquestion_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DiagnosticOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.diagnosticquestion')),
            ],
        ),
    ]
