# Generated by Django 5.2.8 on 2026-03-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='learningplan',
            new_name='analytics_l_user_id_30a038_idx',
            old_name='analytics_plan_user_gen_idx',
        ),
        migrations.RenameIndex(
            model_name='skillgapanalysis',
            new_name='analytics_s_user_id_fb0c20_idx',
            old_name='analytics_skill_user_topic_idx',
        ),
        migrations.RenameIndex(
            model_name='skillgapanalysis',
            new_name='analytics_s_user_id_cdb8a8_idx',
            old_name='analytics_skill_user_status_idx',
        ),
    ]
