# Generated by Django 5.2.8 on 2026-02-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('initial_code', models.TextField()),
                ('solution_code', models.TextField(blank=True, null=True)),
                ('test_cases', models.JSONField()),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'challenges',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.IntegerField()),
                ('title', models.TextField()),
                ('slug', models.TextField()),
                ('content', models.TextField()),
                ('order', models.IntegerField()),
                ('difficulty', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.IntegerField()),
                ('text', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('options', models.JSONField()),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField()),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('lesson_id', models.IntegerField()),
                ('completed', models.BooleanField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('last_code', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_progress',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='original_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
