# Generated by Django 5.2.8 on 2026-02-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_challenge_lesson_module_question_quiz_userprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quiz_completed',
            field=models.BooleanField(default=False),
        ),
    ]
