# Generated by Django 6.0.2 on 2026-02-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_quiz_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='quiz_completed',
        ),
    ]
