# Generated by Django 6.0.2 on 2026-02-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_diagnosticquestionmeta_user_mastery_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diagnostic_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='engagement_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_velocity',
            field=models.FloatField(default=0.0),
        ),
    ]
