# Generated by Django 5.2.8 on 2026-03-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_diagnostic_completed_user_engagement_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_taken_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
