# Generated by Django 5.2.8 on 2026-03-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_certificatetemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='profileImageUrl',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
