# Generated by Django 5.2.8 on 2026-03-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_challenge_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='lesson_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='lesson_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
