# Generated by Django 5.2.8 on 2026-03-12 05:44

from django.db import migrations, connection, OperationalError

class SafeRunSQL(migrations.RunSQL):
    """
    A safer RunSQL that only executes on PostgreSQL and ignores errors
    if the extension is not available in the system.
    """
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            try:
                super().database_forwards(app_label, schema_editor, from_state, to_state)
            except (OperationalError, Exception):
                # We catch general exceptions here to ensure the migration doesn't break
                # local development if the PostgreSQL system lacks pgvector.
                pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            try:
                super().database_backwards(app_label, schema_editor, from_state, to_state)
            except (OperationalError, Exception):
                pass

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('core', '0013_alter_challenge_lesson_id_alter_lesson_module_id_and_more'),
    ]

    operations = [
        SafeRunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;"
        ),
    ]
