# Generated by Django 5.2.8 on 2026-03-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_questionattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
    ]
