# Generated by Django 6.0.3 on 2026-03-14 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_questionattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='created_at',
            new_name='completed_at',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.quiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('user', 'quiz')},
        ),
    ]
