# Generated by Django 5.2.8 on 2026-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_created_at_quizattempt_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='lesson_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosticattempt',
            name='quiz_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosticquestionmeta',
            name='question_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermastery',
            name='module_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='lesson_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
