# Generated by Django 5.2.8 on 2026-03-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_challenge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='challenge_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='quiz_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
