# Generated by Django 6.0.4 on 2026-04-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userprogress_challenge_completed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
