# Generated by Django 5.2.8 on 2026-04-07 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userprogress_challenge_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='verification_code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
