# Generated by Django 6.0.4 on 2026-04-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_certificate_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='DiagnosticQuestionMeta',
        ),
        migrations.DeleteModel(
            name='DiagnosticAttempt',
        ),
    ]
