# Generated by Django 6.0.4 on 2026-04-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_diagnosticattempt_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='required_code_patterns',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
